name: 'Patchdog'
description: > 
  Generate comprehensive rustdoc comments for your project. 
  Requires contents: write and pull-requests: write permissions.
author: 'Yurii Litvinov'


branding:
  color: 'red'     
  icon: 'git-pull-request'

inputs:
  github_token:
    description: 'GitHub token with repo access'
    required: true

  api_key_gemini:
    description: 'Google Gemini API key'
    required: true
  
  base_branch:
    description: Base branch of PR 
    required: true

  head_branch:
    description: Head branch of PR 
    required: true

  assignee:
    description: Who will be assigned to audit the PR initialized by patchdog
    required: true

  api_key_openai:
    description: 'OpenAI API key'
    required: false

  patchdog_name:
    description: Commit signature name
    required: false
    default: Patchdog

  patchdog_email:
    description: Commit signature email
    required: false
    default: some@email.com

outputs: 
  patchdog-run:
    description: 'Pull request containing pending changes from base branch'

runs: 
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - name: Run patchdog # grabs patchdog_config.yml from root of the project
      run: |
        chmod +x action/run.sh
        ./action/run.sh
      shell: bash
      env: 
        API_KEY_GEMINI: ${{ inputs.api_key_gemini }}
        GH_TOKEN: ${{ inputs.github_token }}
        BASE_BRANCH: ${{ inputs.base_branch }}
        HEAD_BRANCH: ${{ inputs.head_branch }}
        ASSIGNEE: ${{ inputs.assignee }}
        COMMIT_EMAIL: ${{ inputs.patchdog_email }}
        COMMIT_NAME: ${{ inputs.patchdog_name }}
        API_KEY_OPENAI: ${{ inputs.api_key_openai }}


