name: 'Patchdog'
description: > 
  Generate comprehensive rustdoc comments for your project. 
  Requires contents: write and pull-requests: write permissions.
author: 'Yurii Litvinov'

inputs:
  github_token:
    description: 'GitHub token with repo access'
    required: true

  api_key_gemini:
    description: 'Google Gemini API key'
    required: true

  api_key_openai:
    description: 'OpenAI API key'
    required: false

  patchdog_name:
    description: Commit signature name
    required: false
    default: Patchdog

  patchdog_email:
    description: Commit signature email
    required: false
    default: some@email.com


outputs: 
  patchdog-run:
    description: 'Pull request containing pending changes from base branch'

runs: 
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0
    - name: Ensure pull_request context
      shell: bash
      run: |
        if [ -z "${{ github.event.pull_request.head.ref }}" ]; then
          echo "This action is to be ran inside PR"
          exit 1
        fi
    - name: Run patchdog # grabs patchdog_config.yml from root of the project
      run: |
        chmod +x action/run.sh
        ./action/run.sh
      shell: bash
      env: 
        API_KEY_GEMINI: ${{ inputs.api_key_gemini }}
        GH_TOKEN: ${{ inputs.github_token }}
        API_KEY_OPENAI: ${{ inputs.api_key_openai }}
        COMMIT_EMAIL: ${{ inputs.patchdog_email }}
        COMMIT_NAME: ${{ inputs.patchdog_name }}
        BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
        ASSIGNEE: ${{ github.event.pull_request.user.login }} 


