[package]
name = "patchdog"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_parsing = { path = "../rust_parsing" }
chatgpt = { path = "../chatgpt" }
gemini = { path = "../gemini" }
git_parsing = { path = "../git_parsing" }
syn = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
snafu = { workspace = true }
anyhow = "1.0.98"
tracing = "0.1.41"
rustc_lexer = "0.1.0"

