[package]
name = "patchdog"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_parsing = { path = "../rust_parsing" }
chatgpt = { path = "../chatgpt" }
gemini = { path = "../gemini" }
git_parsing = { path = "../git_parsing" }
syn = { workspace = true }
dotenv = { workspace = true }
tokio = { workspace = true }
snafu = { workspace = true }
tracing = "0.1.41"
git2 = "0.20.2"
tempfile = "3.20.0"
clap = { workspace = true }