name: Build release and publish

on: 
  push:
    branches: [main]

jobs:
  release-dog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: Debug status
        run: ls
      - name: Extract version from Cargo.toml
        run: echo VERSION=$(grep '^version' crates/patchdog/Cargo.toml | head -n 1 | cut -d '"' -f2) >> $GITHUB_ENV
      - name: Run shell script with build
        run: |
          chmod +x build.sh 
          ./build.sh
      - name: Publish release
        uses: actions/upload-artifact@v4
        with:
          name: Patchdog release
          path: build/patchdog
      - name: Create GitHub release
        run: gh release create v${VERSION} ./build/patchdog --title "First Release" --notes "Autorelease"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
