name: Patchdog from comment 

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  callcomment:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@patchdog')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@patchdog')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@patchdog')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@patchdog') || contains(github.event.issue.title, '@patchdog') || 
        contains(github.event.issue.body, '@patchdog')
      ))
    runs-on: ubuntu-latest
    steps:
      - name: Echo something
        run: echo "Hello, world!"