name: Patchdog from comment 

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  patchdog:
    if: github.event.issue.pull_request != null
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@patchdog')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@patchdog')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@patchdog')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@patchdog') || contains(github.event.issue.title, '@patchdog')))
    runs-on: ubuntu-latest
    steps:
      - name: Print comment info
        run: |
          echo "Comment by: ${{ github.event.comment.user.login }}"
          echo "Comment body: ${{ github.event.comment.body }}"
    