name: Patchdog from comment 

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  patchdog:
    if: contains(github.event.comment.body || '', '@patchdog')
    runs-on: ubuntu-latest
    steps:
      - name: Print trigger message
        run: echo "Comment: ${{ github.event.comment.body }}"

    