name: Patchdog from comment 

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  Comment_echo:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@patchdog')
    steps:
    - name: Print trigger content
      run: |
        echo "Comment: ${{ github.event.comment.body }}"
