name: Run patchdog - AI engine

on:
  pull_request_review:
    types: [submitted]
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: fetch branch
      run: git fetch origin ${{ github.base_ref }}
    - name: make patch
      run: git diff origin/${{ github.base_ref }}...${{ github.head_ref }} > patch.patch
    - name: run patchdog
      run: cargo run -- --file-patch patch.patch
      env:
        API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}
    - name: cleanup patch
      run: rm patch.patch
    - name: update pull request
      run: git diff HEAD 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        