name: Run patchdog - AI engine

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: make patch
      run: git diff HEAD~1 HEAD > patch.patch
    - name: run patchdog
      run: cargo run -- --file-patch patch.patch
      env:
        API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}
    - name: cleanup patch
      run: rm patch.patch
