name: Patchdog debug

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [opened, reopened, edited]
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  run_patchdog:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update version number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: sed -i "s/^version = \".*\"/version = \"1.1.${PR_NUMBER}\"/" crates/patchdog/Cargo.toml
      - name: test branches
        run: | 
          echo "base_branch ${{ github.base_ref }}"
          echo "head_branch: ${{ github.head_ref }}"
      - name: Run Patchdog action
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key_gemini: ${{ secrets.API_KEY_GEMINI }}
          base_branch: ${{ github.event.pull_request.base.ref }}
          head_branch: ${{ github.event.pull_request.head.ref }}
          assignee: ${{ github.event.pull_request.user.login }} 