name: Run patchdog - AI engine

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: move into directory
      run: cd /home/runner/work/patchdog/patchdog
    - name: make patch
      run: git diff HEAD~1 HEAD > patch.patch
    - name: checking out branch
      run: git checkout HEAD
    - name: run patchdog
      run: cargo run -- --file-patch patch.patch
    - name: create pull request
      run: gh pr create -B base_branch -H branch_to_merge --title 'Merge PR $(date)' --body 'Created by patchdog!'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}