name: Run patchdog - AI engine

on:
  pull_request_review:
    types: [submitted]
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  Run_patchdog:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: fetch branch
        run: git fetch origin ${{ github.base_ref }}
      - name: make patch
        run: git diff origin/${{ github.base_ref }}...${{ github.head_ref }} > patch.patch
      - name: run patchdog
        run: cargo run -- --file-patch patch.patch
        env:
          API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}
      - name: show status
        run: git status
      - name: cleanup patch
        run: rm patch.patch
      - name: update pull request
        run: git diff HEAD > patch.patch 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload patch file - review changes before they are applied
        uses: actions/upload-artifact@v4
        with:
          name: patch-file
          path: patch.patch
    - name: make new branch with patch
      run: git checkout -b patchdog-$(uuidgen)
    - name: create pull request with patch
      run: gh pr create --title "Patchdog patch" --body "Patchdog patch" --head patchdog --base ${{ github.base_ref }} --assignee ${{ github.event.pull_request.user.login }} --draft