name: Run patchdog - AI engine

on:
  pull_request_review:
    types: [submitted]
  pull_request:
env:
  CARGO_TERM_COLOR: always

jobs:
  Run_patchdog:

    runs-on: ubuntu-latest
    env:
      PATCHDOG_BRANCH: patchdog-$(uuidgen)
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Check for merge conflicts # when deployed, should be changed to exit 1
        run: |
          if  git grep -n -e '<<<<<<< ' --  --exclude='patchdog.yml'  > /dev/null; then
            git grep -n '<<<<<<< HEAD'
            exit 0
          else
            exit 0
          fi

      - name: Fetch branch
        run: git fetch origin ${{ github.base_ref }}
      - name: Make patch
        run: git diff origin/${{ github.base_ref }}...${{ github.head_ref }} > base_head.patch
      - name: Run patchdog
        run: cargo run -- --file-patch base_head.patch
        env:
          API_KEY_GEMINI: ${{ secrets.API_KEY_GEMINI }}
      - name: Cleanup patch
        run: rm base_head.patch
      - name: Show status
        run: git status
      - name: Generate patch
        run: git diff HEAD > $PATCHDOG_BRANCH.patch 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload patch file - review changes before they are applied
        uses: actions/upload-artifact@v4
        with:
          name: patch-file
          path: $PATCHDOG_BRANCH.patch
      - name: Cleanup patch
        run: rm $PATCHDOG_BRANCH.patch
      - name: Checkout into new branch, create PR
        run: |
          git config --global user.email "noreply@patchdog.ua"
          git config --global user.name "Patchdog Patchdogovich"
          git commit -m "Patchdog-$PATCHDOG_BRANCH"
          git checkout -b $PATCHDOG_BRANCH
          gh pr create --title "Patchdog-$PATCHDOG_BRANCH" --body "Patchdog-$PATCHDOG_BRANCH" --head $PATCHDOG_BRANCH --base ${{ github.head_ref }} --assignee ${{ github.event.pull_request.user.login }} --draft
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}