name: Patchdog debug

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run_patchdog:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - name: Patchdog
        uses: YuraLitvinov/patchdog@v1.2.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key_gemini: ${{ secrets.API_KEY_GEMINI }}
