name: Patchdog debug

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  run_patchdog:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write

    steps:
      - name: Update version number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: sed -i "s/^version = \".*\"/version = \"1.1.${PR_NUMBER}\"/" crates/patchdog/Cargo.toml
      - name: Run Patchdog action
        uses: ./action/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          api_key_gemini: ${{ secrets.API_KEY_GEMINI }}
