name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run try
      run: cargo run -- --dir-path ./
